### ISSUE TITLE
Implement a basic mechanism to implement transactional map R/Ws

### ISSUE THREAD

**Issue by rjsu26** [rosalab/linux#2]
This issue is to split the task of making BPF map read and writes as transactional using a basic commit based mechanism. 
Following are the subtasks: 

- [ ] Make a pair of complementing helper functions : `tx_begin()` and `tx_end()` which will mark the start and end of a transactional block. The verifier should enforce one on the presence of another.
- [ ]  Create a per-BPF program scratch space where all writes will be saved temporarily until the `tx_end()` helper is called. 
- [ ] All map reads and writes between a _tx_ block has to be modified by the verifier to write to a temp map/space. 
- [ ] The tx_end helper should go through the temp saved data and commit them to the actual map. 
- [ ] Add an internal static function which will handle the rollback when the BPF program couldn't complete a _tx_ block.

**Comment by sidchintamaneni** [comment]
I think we need a rollback helper as well, what do you think?

**Comment by rjsu26** [comment]
> I think we need a rollback helper as well, what do you think?

Yeah that will be an internal rollback handler which a termination or exception handler will call. Added to the list
